
apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage-config
  namespace: default
data:
  settings.yaml: |
    title: Home Dashboard
    favicon: https://gethomepage.dev/img/favicon.ico
    theme: dark
    color: slate
    layout:
      - Services:
          style: row
          columns: 3
  
  services.yaml: |
    - Infrastructure:
        - ArgoCD:
            icon: argocd.png
            href: https://argo-cd.tyvan.dev
            description: GitOps CD tool
  
  widgets.yaml: |
    - search:
        provider: google
        target: _blank
    - datetime:
        text_size: xl
        format:
          dateStyle: short
          timeStyle: short
          hour12: false
  
  bookmarks.yaml: |
    - Developer:
        - Github:
            - icon: github.png
              href: https://github.com/
  
  docker.yaml: ""
  kubernetes.yaml: ""
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homepage
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homepage
  template:
    metadata:
      labels:
        app: homepage
    spec:
      containers:
      - name: homepage
        image: ghcr.io/gethomepage/homepage:latest
        ports:
        - containerPort: 3000
          name: http
        volumeMounts:
        - name: config
          mountPath: /app/config
        env:
        - name: TZ
          value: "Asia/Ho_Chi_Minh"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: config
        configMap:
          name: homepage-config
---
apiVersion: v1
kind: Service
metadata:
  name: homepage-service
  namespace: default
spec:
  selector:
    app: homepage
  ports:
  - port: 3000
    targetPort: 3000
    name: http
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homepage-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - hub.tyvan.dev
    secretName: homepage-tls-letsencrypt
  rules:
  - host: hub.tyvan.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: homepage-service
            port:
              number: 3000
